name: 'Analyze XCode Results'
description: 'Provide a description here'
author: 'Thomas Bartelmess'
inputs:
  results:
    required: true
    description: 'Path to a the xcresult bundle'
  pathPrefix:
    required: false
    description: 'Build Path Prefix'
    default: ${{ github.workspace }}
  GITHUB_TOKEN:
    required: true
    description: "GitHub token to create the check"
  title:
    required: true
    description: "Title for the check results"
    default: "Test Results"


runs:
  using: 'node12'
  main: 'dist/index.js'
