name: 'Analyze XCode Results'
description: 'Provide a description here'
author: 'Thomas Bartelmess'
inputs:
  results: # change this
    required: true
    description: 'Path to a the xcresult buindle'
runs:
  using: 'node12'
  main: 'dist/index.js'
