name: 'Analyze XCode Results'
description: 'Provide a description here'
author: 'Thomas Bartelmess'
inputs:
  results:
    required: true
    description: 'Path to a the xcresult bundle'
  pathPrefix:
    required: false
    description: 'Build Path Prefix'
    default: ${{ github.workspace }}
  githubToken:
    required: true
    description: "GitHub token to create the check"

runs:
  using: 'node12'
  main: 'dist/index.js'
